### ISSUE TITLE
Invalid volume.name of format xxxx.xxx

### ISSUE THREAD

**Issue by mdedetrich** [micahhausler/container-transform#27]
When specifying volumes like this

``` yml
  volumes:
    - '/etc/certs/cert.crt:/etc/nginx/certs/cert.crt'
    - '/etc/certs/cert.key:/etc/nginx/certs/cert.key'
```

The `container-transform` will output something like this

``` json
    "volumes": [
        {
            "host": {
                "sourcePath": "/etc/certs/cert.crt"
            },
            "name": "EtcCertsCert.Crt"
        },
        {
            "host": {
                "sourcePath": "/etc/certs/cert.key"
            },
            "name": "EtcCertsCert.Key"
        }
    ]
```

and

``` json
            "mountPoints": [
                {
                    "containerPath": "somePath.crt",
                    "sourceVolume": "EtcCertsCert.Crt"
                },
                {
                    "containerPath": "somePath.key",
                    "sourceVolume": "EtcCertsCert.Key"
                }
            ],
```

Unfortunately, `EtcCertsCert.Crt` and `EtcCertsCert.Key` are not valid volume names (Amazon ECS will complain with `Invalid volume.name`). I had to manually replace `EtcCertsCert.Crt` with `EtcCertsCert_Crt` and `EtcCertsCert.Key` with `EtcCertsCert_Key`.

If a volume.label happens to be a direct filename, the `.` needs to be replaced with some other valid character

**Comment by micahhausler** [comment]
Thanks for pointing this out! I'll have a fix out for that shortly
