### ISSUE TITLE
Add required option

### ISSUE THREAD

**Issue by mdedetrich** [micahhausler/container-transform#32]
Similar to `cpu_shares` and `mem_limit` (which aren't official options for `docker-compose.yml`, but were added to container transform so they can be outputted in the ECS task JSON definition), we should add the `required` option, which translates directly to the required option in the TASK definition JSON

Should default to `true` when it doesn't exist (as it currently does)

**Comment by micahhausler** [comment]
Well the `cpu_shares` and `mem_limit` are official docker-compose options, see the last point in the [yml reference docs](https://docs.docker.com/compose/yml/#working-dir-entrypoint-user-hostname-domainname-mac-address-mem-limit-memswap-limit-privileged-restart-stdin-open-tty-cpu-shares-cpuset-read-only-volume-driver).

That being said, I do see the usefulness of specifying a non-compose-standard `default: false` option in the yml so users wouldn't have to hand-hack `\t"default": false,` in cases where it would be false. I'll look into it and see if compose doesn't barf with a 'default' parameter and it should be pretty straight forward to add. I'll just need to ensure that a 'default' parameter doesn't make it through the reverse direction, from a `task.json` to a `docker-compose.yml`

**Comment by mdedetrich** [comment]
On a similar note, is `restarts` essentially the same as `required`?

In terms of what they mean in the english language, they are definitely not the same thing, but it amounts to the same result. i.e., `restarts:true` results in the container being restarted should it exist, which is what AWS ECS does if you have `required:true`

**Comment by philipn** [comment]
If this were added, I'd suggest using the docker `label` construct, which can be specified in a compose file. I'm using labels for our deployment to specify stuff like this, and then I transform the task file accordingly.

**Comment by micahhausler** [comment]
I think in the interest of keeping the tool more generic, I'm going to reject this idea. It would become really confusing to maintain for support non-valid parameters in multiple formats.

**Comment by philipn** [comment]
What we ended up doing here is post-processing the outputted task
definition to add the `required` parameter before sending the definition to
ECS.
