### ISSUE TITLE
Add log_driver options

### ISSUE THREAD

**Issue by mdedetrich** [micahhausler/container-transform#33]
In the latest release of amazon aws-container-agent (https://github.com/aws/amazon-ecs-agent/issues/123), they have added support for logging. The JSON, like other options in the AWS task definition, seems to mimic the one from docker-compose

See `log_driver` at https://docs.docker.com/compose/yml/ and `logDriver` at http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html

**Comment by micahhausler** [comment]
This would be a great addition, thanks for the reference links!
