### ISSUE TITLE
Support 'extends' syntax

### ISSUE THREAD

**Issue by rpherrera** [micahhausler/container-transform#36]
When converting from a docker-compose file which relies on 'extends' keyword, then container-transform does not follows the definition from that service.

It would be useful to see it being supported.

**Comment by micahhausler** [comment]
This is a good idea, I'm not sure when I'll have the time in the near term, but I'd welcome a PR

**Comment by micahhausler** [comment]
Since "extends" only affects docker-compose, and involves file lookups with non-trivial merging, I'm going to reject this.

**Comment by moleCuleFFF** [comment]
+ 1 and a bump for this feature :D Its a real paint to do two exports and then use a diff tool to merge them :(
