### ISSUE TITLE
Support env_file

### ISSUE THREAD

**Issue by dhulihan** [micahhausler/container-transform#44]
This would be a killer feature for container-transform.

**Comment by dhulihan** [comment]
Nice! Good progress, but PR #50 omits env-file from ECS when provided (since ECS doesn't support env-file in task definitions, totally understandable). What do you think about reading in `env-file` and converting line entries to `environment` members?

**Comment by micahhausler** [comment]
I'd rather not enable unsupported features, add as few surprises as possible, and keep the tool simple to maintain and understand. 

While it is a manual step, you could still script the dumping an env file to your compose:

``` bash
cat <<EOF >app.env
TERM=xterm
CT_INPUT_TYPE=compose
CT_OUTPUT_TYPE=ecs
EOF
cat app.env | sed -e 's/=/: /g' >> docker-compose.yml
```

**Comment by dhulihan** [comment]
No worries, thanks for the consideration and snippet.
