### ISSUE TITLE
Invalid YAML output

### ISSUE THREAD

**Issue by numtel** [micahhausler/container-transform#45]
Not all string values are quoted in the YAML output when I convert ecs to compose. Some work but I've got an AWS ARN with some slashes that causes docker-compose to not accept the file.

**Comment by micahhausler** [comment]
Could you maybe give an anonymized example?

**Comment by numtel** [comment]
I'm sorry to have made the issue. I can no longer reproduce it. I've been using this script to grab the task definition from AWS and then make it usable on the local machine:

``` sh
#!/bin/bash
# Download task definition, remove custom logging, convert to compose
TASK_NAME=something
aws ecs describe-task-definition --task-definition $TASK_NAME \
  | jq '.taskDefinition | del(.containerDefinitions[].logConfiguration)' \
  | docker run --rm -i micahhausler/container-transform \
      --input-type ecs --output-type compose \
  > docker-compose.yml
```
