### ISSUE TITLE
Any Updates?

### ISSUE THREAD

**Issue by bitbier** [micahhausler/container-transform#72]
Just writing to see if there are any updates happening to this project? It seems like nothing has been happening since January, 2017; however, the last pip release was in [June of last year](https://pypi.python.org/pypi/container-transform/1.1.4) for version 1.1.4. I'm interested in a new version as currently the volume parsing is broken for read-write volume parsing from docker-compose, but it appears to be fixed in master.

**Comment by micahhausler** [comment]
Yes, I'm still taking PR's but not actively developing it. I'll release a new version this week, I've been meaning to automate Pypi releases via TravisCi and will get that set up as well

**Comment by micahhausler** [comment]
I merged #73 and automated the deployment process, let me know if you have an issues!
